# Generated by Django 3.0.8 on 2020-07-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=45)),
                ('last', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('bday', models.DateField(null=True)),
                ('pw', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeout_date', models.DateField()),
                ('bag_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fullness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trashtype', models.CharField(max_length=180)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_trash', to='waste_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=180)),
                ('earned_on', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_badges', to='waste_app.User')),
            ],
        ),
    ]
