# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0002_auto_20191119_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='trashtype',
            field=models.CharField(default='Trashbag', max_length=180),
            preserve_default=False,
        ),
    ]
