# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0003_trash_trashtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=180)),
                ('earned_on', models.DateField(auto_now_add=True)),
                ('trashlink', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='waste_app.Trash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_badges', to='waste_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='badges',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badges',
        ),
    ]
