# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_app', '0004_auto_20191121_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='trashlink',
        ),
    ]
